force-app/default/objects/Address__c/Address__c.object-meta.xml
<CustomObject>
    <label>Address</label>
    <nameField>
        <displayFormat>ADRID-{0000}</displayFormat>
        <label>Address Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Address</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/default/objects/Address__c/fields/Applicant__c.field-meta.xml
<CustomField>
    <fullName>Applicant__c</fullName>
    <label>Applicant</label>
    <referenceTo>Applicant__c</referenceTo>
    <relationshipLabel>Address</relationshipLabel>
    <relationshipName>Address</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/default/objects/Address__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <description>Ahmadnagar
Akola
Amravati
Aurangabad
Bhandara
Bhusawal
Bid
Buldhana
Chandrapur
Daulatabad
Dhule
Jalgaon
Kalyan
Karli
Kolhapur
Mahabaleshwar
Malegaon
Matheran
Mumbai
Nagpur
Nanded
Nashik
Osmanabad
Pandharpur
Parbhani
Pune
Ratnagiri
Sangli
Satara
Sevagram
Solapur
Thane
Ulhasnagar
Vasai-Virar
Wardha
Yavatmal</description>
    <label>City</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ahmadnagar</fullName>
            </value>
            <value>
                <fullName>Akola</fullName>
            </value>
            <value>
                <fullName>Amravati</fullName>
            </value>
            <value>
                <fullName>Aurangabad</fullName>
            </value>
            <value>
                <fullName>Bhandara</fullName>
            </value>
            <value>
                <fullName>Bhusawal</fullName>
            </value>
            <value>
                <fullName>Bid</fullName>
            </value>
            <value>
                <fullName>Buldhana</fullName>
            </value>
            <value>
                <fullName>Chandrapur</fullName>
            </value>
            <value>
                <fullName>Daulatabad</fullName>
            </value>
            <value>
                <fullName>Dhule</fullName>
            </value>
            <value>
                <fullName>Jalgaon</fullName>
            </value>
            <value>
                <fullName>Kalyan</fullName>
            </value>
            <value>
                <fullName>Karli</fullName>
            </value>
            <value>
                <fullName>Kolhapur</fullName>
            </value>
            <value>
                <fullName>Mahabaleshwar</fullName>
            </value>
            <value>
                <fullName>Malegaon</fullName>
            </value>
            <value>
                <fullName>Matheran</fullName>
            </value>
            <value>
                <fullName>Mumbai</fullName>
            </value>
            <value>
                <fullName>Nagpur</fullName>
            </value>
            <value>
                <fullName>Nanded</fullName>
            </value>
            <value>
                <fullName>Nashik</fullName>
            </value>
            <value>
                <fullName>Osmanabad</fullName>
            </value>
            <value>
                <fullName>Pandharpur</fullName>
            </value>
            <value>
                <fullName>Parbhani</fullName>
            </value>
            <value>
                <fullName>Pune</fullName>
            </value>
            <value>
                <fullName>Ratnagiri</fullName>
            </value>
            <value>
                <fullName>Sangli</fullName>
            </value>
            <value>
                <fullName>Satara</fullName>
            </value>
            <value>
                <fullName>Sevagram</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/default/objects/Address__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <description>India
China
Japan
Russia
Canada
America
England</description>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>India</fullName>
            </value>
            <value>
                <fullName>China</fullName>
            </value>
            <value>
                <fullName>Japan</fullName>
            </value>
            <value>
                <fullName>Russia</fullName>
            </value>
            <value>
                <fullName>Canada</fullName>
            </value>
            <value>
                <fullName>America</fullName>
            </value>
            <value>
                <fullName>England</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/default/objects/Address__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <description>Uttar Pradesh
 Rajasthan
 Gujarat
Punjab
 Himachal Pradesh
 Andhra Pradesh
7. Arunachal Pradesh
8. Assam
9. Bihar
10. Chhattisgarh
11. Jammu and Kashmir
12. Haryana
13. Maharashtra
14. Meghalaya
15. Mizoram 
16. Nagaland
17. Karnataka
18. Jharkhand
19. Madhya Pradesh
20. Kerala
21. Odisha
22. Sikkim
23. Tamil Nadu
24. Telangana
25. Tripura
26. West Bengal
27. Manipur
28. Uttarakhand
 Goa</description>
    <label>State</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Uttar Pradesh</fullName>
            </value>
            <value>
                <fullName>Rajasthan</fullName>
            </value>
            <value>
                <fullName>Gujarat</fullName>
            </value>
            <value>
                <fullName>Punjab</fullName>
            </value>
            <value>
                <fullName>Himachal Pradesh</fullName>
            </value>
            <value>
                <fullName>Andhra Pradesh</fullName>
            </value>
            <value>
                <fullName>Arunachal Pradesh</fullName>
            </value>
            <value>
                <fullName>Assam</fullName>
            </value>
            <value>
                <fullName>Bihar</fullName>
            </value>
            <value>
                <fullName>Chhattisgarh</fullName>
            </value>
            <value>
                <fullName>Jammu and Kashmir</fullName>
            </value>
            <value>
                <fullName>Haryana</fullName>
            </value>
            <value>
                <fullName>Maharashtra</fullName>
            </value>
            <value>
                <fullName>Meghalaya</fullName>
            </value>
            <value>
                <fullName>Mizoram</fullName>
            </value>
            <value>
                <fullName>Nagaland</fullName>
            </value>
            <value>
                <fullName>Karnataka</fullName>
            </value>
            <value>
                <fullName>Jharkhand</fullName>
            </value>
            <value>
                <fullName>Madhya Pradesh</fullName>
            </value>
            <value>
                <fullName>Kerala</fullName>
            </value>
            <value>
                <fullName>Odisha</fullName>
            </value>
            <value>
                <fullName>. Sikkim</fullName>
            </value>
            <value>
                <fullName>Tamil Nadu</fullName>
            </value>
            <value>
                <fullName>Telangana</fullName>
            </value>
            <value>
                <fullName>Tripura</fullName>
            </value>
            <value>
                <fullName>West Bengal</fullName>
            </value>
            <value>
                <fullName>Manipur</fullName>
            </value>
            <value>
                <fullName>Uttarakhand</fullName>
            </value>
            <value>
                <fullName>Goa</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/default/objects/Applicant__c/Applicant__c.object-meta.xml
<CustomObject>
    <label>Applicant</label>
    <nameField>
        <displayFormat>APID-{0000}</displayFormat>
        <label>Applicants ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applicants</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/default/objects/Applicant__c/fields/Police_Verification__c.field-meta.xml
<CustomField>
    <fullName>Police_Verification__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Police Verification</label>
    <type>Checkbox</type>
</CustomField>

force-app/default/classes/addressToApplicantClass.cls
global class addressToApplicantClass implements Database.Batchable <sObject>, Database.Stateful{
            Set<Id> successRecordsSet = new Set<Id>();
    		Set<Id> failedRecordsSet = new Set<Id>();
     
			global Database.QueryLocator start (Database.BatchableContext BC){
			return Database.getQueryLocator('Select Id, City__c, State__c, Country__c , Applicant__r.Id, Applicant__r.Name, Applicant__r.Police_Verification__c from Address__c where City__c = \'Nagpur\' and Applicant__r.Police_Verification__c != true ')  ;
			}
   
   
			global void execute(Database.BatchableContext BC, List <Address__c> adrList){
     

			Set <Id> appIdSet = new Set <Id> ();
			if(!adrList.isEmpty()){
			for(Address__c objAdr : adrList){
			if(objAdr.Applicant__c != Null){
			appIdSet.add(objAdr.Applicant__c);
			}
			
			}
            }
			map <Id, Applicant__c> appMap = new map <Id, Applicant__c>();
                for ( Applicant__c objApp : [Select Id, First_Name__c, Last_Name__c, Police_Verification__c from Applicant__c where Id IN : appIdSet]){
                    appMap.put(objApp.Id, objApp );
                }
					
			if(!appMap.isEmpty()){
			for(Address__c objAdr : adrList){
			if(appMap.containsKey(objAdr.Applicant__c)){
			appMap.get(objAdr.Applicant__c).Police_Verification__c = true;
                         
			}
			}
			
			Database.SaveResult [] result = Database.Update(appMap.values(),false);
                
            List<Applicant__c> appList = appMap.values();    
			
            Integer index=0;
            
            for(Database.SaveResult sr : result){
                if(sr.isSuccess()){
                    System.debug('Success = '+appList[index].Id);
                    successRecordsSet.add(appList[index].Id);
                    index++;
                }
                else{
                    System.debug('Failed = '+appList[index].Id);
                    failedRecordsSet.add(appList[index].Id);
                    index++;
                }
            }
                        
        }

			}
			    
			    global void finish(Database.BatchableContext BC){
        List<Messaging.SingleEmailMessage> mailList = new List<Messaging.SingleEmailMessage>();
        Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
        mail.setToAddresses(new String[] {'bhagya88058@gmail.com'});
        mail.setSenderDisplayName('Bhagyashree');
        mail.setSubject('Success and Failed Record');
        mail.setPlainTextBody('Success = '+successRecordsSet+' Failed '+failedRecordsSet); 
        mailList.add(mail);            
        if(!mailList.isEmpty()){
            Messaging.sendEmail(mailList,false);  
        }
        
    }
 }