force-app/default/objects/Address__c/Address__c.object-meta.xml
<CustomObject>
    <label>Address</label>
    <nameField>
        <displayFormat>ADRID-{0000}</displayFormat>
        <label>Address Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Address</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/default/objects/Address__c/fields/Applicant__c.field-meta.xml
<CustomField>
    <fullName>Applicant__c</fullName>
    <label>Applicant</label>
    <referenceTo>Applicant__c</referenceTo>
    <relationshipLabel>Address</relationshipLabel>
    <relationshipName>Address</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/default/objects/Address__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <description>Ahmadnagar
Akola
Amravati
Aurangabad
Bhandara
Bhusawal
Bid
Buldhana
Chandrapur
Daulatabad
Dhule
Jalgaon
Kalyan
Karli
Kolhapur
Mahabaleshwar
Malegaon
Matheran
Mumbai
Nagpur
Nanded
Nashik
Osmanabad
Pandharpur
Parbhani
Pune
Ratnagiri
Sangli
Satara
Sevagram
Solapur
Thane
Ulhasnagar
Vasai-Virar
Wardha
Yavatmal</description>
    <label>City</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ahmadnagar</fullName>
            </value>
            <value>
                <fullName>Akola</fullName>
            </value>
            <value>
                <fullName>Amravati</fullName>
            </value>
            <value>
                <fullName>Aurangabad</fullName>
            </value>
            <value>
                <fullName>Bhandara</fullName>
            </value>
            <value>
                <fullName>Bhusawal</fullName>
            </value>
            <value>
                <fullName>Bid</fullName>
            </value>
            <value>
                <fullName>Buldhana</fullName>
            </value>
            <value>
                <fullName>Chandrapur</fullName>
            </value>
            <value>
                <fullName>Daulatabad</fullName>
            </value>
            <value>
                <fullName>Dhule</fullName>
            </value>
            <value>
                <fullName>Jalgaon</fullName>
            </value>
            <value>
                <fullName>Kalyan</fullName>
            </value>
            <value>
                <fullName>Karli</fullName>
            </value>
            <value>
                <fullName>Kolhapur</fullName>
            </value>
            <value>
                <fullName>Mahabaleshwar</fullName>
            </value>
            <value>
                <fullName>Malegaon</fullName>
            </value>
            <value>
                <fullName>Matheran</fullName>
            </value>
            <value>
                <fullName>Mumbai</fullName>
            </value>
            <value>
                <fullName>Nagpur</fullName>
            </value>
            <value>
                <fullName>Nanded</fullName>
            </value>
            <value>
                <fullName>Nashik</fullName>
            </value>
            <value>
                <fullName>Osmanabad</fullName>
            </value>
            <value>
                <fullName>Pandharpur</fullName>
            </value>
            <value>
                <fullName>Parbhani</fullName>
            </value>
            <value>
                <fullName>Pune</fullName>
            </value>
            <value>
                <fullName>Ratnagiri</fullName>
            </value>
            <value>
                <fullName>Sangli</fullName>
            </value>
            <value>
                <fullName>Satara</fullName>
            </value>
            <value>
                <fullName>Sevagram</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/default/objects/Applicant__c/Applicant__c.object-meta.xml
<CustomObject>
    <label>Applicant</label>
    <nameField>
        <displayFormat>APID-{0000}</displayFormat>
        <label>Applicants ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applicants</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/default/objects/Applicant__c/fields/List_of_Addresses__c.field-meta.xml
<CustomField>
    <fullName>List_of_Addresses__c</fullName>
    <label>List of Addresses</label>
    <type>TextArea</type>
</CustomField>

force-app/default/objects/Applicant__c/fields/Police_Verification__c.field-meta.xml
<CustomField>
    <fullName>Police_Verification__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Police Verification</label>
    <type>Checkbox</type>
</CustomField>

force-app/default/classes/BatchAddressToApplicant.cls
global class BatchAddressToApplicant implements Database.Batchable<sObject>{

    global Database.QueryLocator start(Database.BatchableContext BC){
        return Database.getQueryLocator(' Select Id, Name, City__c, Pin_Code__c,Applicant__r.Id, Applicant__r.Police_Verification__c from Address__c where City__c = \'Nagpur\' and Pin_code__c like \'44%\' and Applicant__r.Police_Verification__c =true ');
    }
    
    global void execute(Database.BatchableContext BC, List<Address__c> adrList){
        
        Set<Id> appIDSet = new Set<Id>();
        if(!adrList.isEmpty()){
            for(Address__c objAdr : adrList){
                if(objAdr.Applicant__c !=null){
                    appIDSet.add(objAdr.Applicant__c);
                }
            }
        }
        
        Map<Id,Applicant__c> appMap = new Map<Id,Applicant__c>([select Id, List_of_Addresses__c from Applicant__c where Id IN :appIDSet]);
    
        if(!appMap.isEmpty()){
            for(Address__c objAdr : adrList){
                if(appMap.containsKey(objAdr.Applicant__c)){
                    if(String.isBlank(appMap.get(objAdr.Applicant__c).List_of_Addresses__c)){
                       appMap.get(objAdr.Applicant__c).List_of_Addresses__c =objAdr.City__c+' '+objAdr.Pin_Code__c; 
                    }
                    else{
                        appMap.get(objAdr.Applicant__c).List_of_Addresses__c = appMap.get(objAdr.Applicant__c).List_of_Addresses__c+'\n'+objAdr.City__c+' '+objAdr.Pin_Code__c;
                    }
                }
            }
            
            Database.update(appMap.values(),false);
        } 
    }
    
    global void finish(Database.BatchableContext BC){
        
    }
}