force-app/default/objects/Applicant__c/Applicant__c.object-meta.xml
<CustomObject>
    <label>Applicant</label>
    <nameField>
        <displayFormat>APID-{0000}</displayFormat>
        <label>Applicants ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applicants</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/default/objects/Applicant__c/fields/MobileActive__c.field-meta.xml
<CustomField>
    <fullName>MobileActive__c</fullName>
    <defaultValue>false</defaultValue>
    <label>MobileActive</label>
    <type>Checkbox</type>
</CustomField>

force-app/default/objects/Applicant__c/fields/MobileOperator__c.field-meta.xml
<CustomField>
    <fullName>MobileOperator__c</fullName>
    <label>MobileOperator</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/default/classes/MobileAPIClass.cls
public with sharing class MobileAPIClass {
    
    @AuraEnabled
    public static void getMobileVerify(Id applicantRecordId){
        system.debug(applicantRecordId);
 
        string mobileNumber =[select Id,Name,Mobile_Number__c from Applicant__c where ID=:applicantRecordId].Mobile_Number__c;

        Http http=new Http();
        HttpRequest request =new HttpRequest();
        request.setEndpoint('https://api.veriphone.io/v2/verify?phone='+mobileNumber+'&key=9493770FAD834D73ACC5D34A3CD51EA9');
        request.setMethod('GET');

        HttpResponse response =  http.send(request);

        system.debug('Response Code ='+response.getStatusCode());
        system.debug('Response Body ='+response.getBody());

        if(response.getStatusCode()==200){
            ApplicantWrapper objWrap=ApplicantWrapper.parse(response.getBody());

            Applicant__c objApp=new Applicant__c(Id=applicantRecordId);
            objApp.MobileOperator__c=objWrap.carrier;

            if(objWrap.phone_valid){
                objApp.MobileActive__c=true;
            }
            else{
                objApp.MobileActive__c=false;
            }
            try {
                database.update(objApp,false);
            } catch (Exception e) {
                system.debug(e);
            }

            
        }
    }
    
}